<a href="https://colab.research.google.com/github/MagicMoleMM/ML/blob/main/TF_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
import numpy as np
from tensorflow.python.keras.layers import Conv2D

In [6]:
signal = np.array([[3,3,2,1,0],
                   [0,0,1,3,1],
                   [3,1,2,2,3],
                   [2,0,0,2,2],
                   [2,0,0,0,1]])

conv_layer = Conv2D(kernel_size=(3,3), filters=1, use_bias=False)


In [8]:
signal = signal.reshape(1,5,5,1).astype(np.float32)
signal.shape

(1, 5, 5, 1)

In [9]:
output = conv_layer(signal)
output

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[-0.9491613 ],
         [ 0.16412461],
         [ 0.45846105]],

        [[-1.4079695 ],
         [-0.05528331],
         [ 1.2055368 ]],

        [[-2.047749  ],
         [-0.48865646],
         [-0.6425277 ]]]], dtype=float32)>

In [11]:
conv_layer.get_weights()[0].shape

(3, 3, 1, 1)

In [12]:
from tensorflow.python.ops.numpy_ops import float32
kernel = np.array([[0,1,2],
                   [2,2,0],
                   [0,1,2]])
kernel = kernel.reshape(3,3,1,1).astype(float32)

In [14]:
conv_layer.set_weights([kernel])
conv_layer(signal)

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[12.],
         [12.],
         [17.]],

        [[10.],
         [17.],
         [19.]],

        [[ 9.],
         [ 6.],
         [14.]]]], dtype=float32)>